
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localhost # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: localhost # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: localhost # The PostgreSQL default database (automatically created at first launch)

    networks:
      - danediary
    volumes:
      - ./data/:/var/lib/postgresql/data/
      
networks: 
  danediary:
    driver: bridge