
services:
  primary:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localhost # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: localhost # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: localhost # The PostgreSQL default database (automatically created at first launch)
    networks:
      - danediary
    volumes:
      - ./data/primary:/var/lib/postgresql/data/
  secondary:
    image: 'valkey/valkey'
    ports:
      - 6379:6379
    networks:
      - danediary
    volumes:
      - ./data/secondary:/data


networks: 
  danediary:
    name: auth
    driver: bridge